[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -Dspring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway -Dspring.datasource.username=postgres -Dspring.datasource.password=GGNZoZEHbsKWBPdZHKZFFbQWRHkJeJnJ -Dspring.datas